// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PowerUnit.Migrations
{
    [DbContext(typeof(PowerUnitIEC104ServerSqliteDbContext))]
    [Migration("20250827115514_Migration_00002_Add_Content")]
    partial class Migration_00002_Add_Content
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("PowerUnit.Infrastructure.IEC104ServerDb.IEC104GroupItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<byte>("Group")
                        .HasColumnType("INTEGER")
                        .HasColumnName("group");

                    b.Property<long>("MappingId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mapping_id");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("MappingId")
                        .HasDatabaseName("ix_groups_mapping_id");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("PowerUnit.Infrastructure.IEC104ServerDb.IEC104MappingItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<ushort>("Address")
                        .HasColumnType("INTEGER")
                        .HasColumnName("address");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("equipment_id");

                    b.Property<string>("ParameterId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("parameter_id");

                    b.Property<int>("ServerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("server_id");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("source_id");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type_id");

                    b.HasKey("Id")
                        .HasName("pk_mappings");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_mappings_type_id");

                    b.HasIndex(new[] { "ServerId", "SourceId", "EquipmentId", "ParameterId", "Address", "TypeId" }, "IX_IEC104MappingItem")
                        .IsUnique()
                        .HasDatabaseName("ix_mappings_server_id_source_id_equipment_id_parameter_id_address_type_id");

                    b.ToTable("mappings", (string)null);
                });

            modelBuilder.Entity("PowerUnit.Infrastructure.IEC104ServerDb.IEC104ServerApplicationLayerOptionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CheckCommonASDUAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("check_common_asdu_address");

                    b.Property<int>("SporadicSendEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("sporadic_send_enabled");

                    b.HasKey("Id")
                        .HasName("pk_application_layer_options");

                    b.ToTable("application_layer_options", (string)null);
                });

            modelBuilder.Entity("PowerUnit.Infrastructure.IEC104ServerDb.IEC104ServerChannelLayerOptionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("MaxQueueSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(100)
                        .HasColumnName("max_queue_size");

                    b.Property<byte>("Timeout0Sec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)30)
                        .HasColumnName("timeout0sec");

                    b.Property<byte>("Timeout1Sec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)15)
                        .HasColumnName("timeout1sec");

                    b.Property<byte>("Timeout2Sec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)10)
                        .HasColumnName("timeout2sec");

                    b.Property<byte>("Timeout3Sec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)20)
                        .HasColumnName("timeout3sec");

                    b.Property<int>("UseFragmentSend")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("use_fragment_send");

                    b.Property<ushort>("WindowKSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((ushort)12)
                        .HasColumnName("window_k_size");

                    b.Property<ushort>("WindowWSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((ushort)8)
                        .HasColumnName("window_w_size");

                    b.HasKey("Id")
                        .HasName("pk_channel_layer_options");

                    b.ToTable("channel_layer_options", (string)null);
                });

            modelBuilder.Entity("PowerUnit.Infrastructure.IEC104ServerDb.IEC104ServerItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ApplicationLayerOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("application_layer_option_id");

                    b.Property<int>("ChannelLayerOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("channel_layer_option_id");

                    b.Property<ushort>("CommonASDUAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((ushort)1)
                        .HasColumnName("common_asdu_address");

                    b.Property<int>("Enable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("enable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("name");

                    b.Property<int>("Port")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(2404)
                        .HasColumnName("port");

                    b.HasKey("Id")
                        .HasName("pk_servers");

                    b.HasIndex("ApplicationLayerOptionId")
                        .HasDatabaseName("ix_servers_application_layer_option_id");

                    b.HasIndex("ChannelLayerOptionId")
                        .HasDatabaseName("ix_servers_channel_layer_option_id");

                    b.ToTable("servers", (string)null);
                });

            modelBuilder.Entity("PowerUnit.Infrastructure.IEC104ServerDb.IEC104TypeItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_types");

                    b.ToTable("types", (string)null);
                });

            modelBuilder.Entity("PowerUnit.Infrastructure.IEC104ServerDb.IEC104GroupItem", b =>
                {
                    b.HasOne("PowerUnit.Infrastructure.IEC104ServerDb.IEC104MappingItem", "Mapping")
                        .WithMany()
                        .HasForeignKey("MappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_groups_mappings_mapping_id");

                    b.Navigation("Mapping");
                });

            modelBuilder.Entity("PowerUnit.Infrastructure.IEC104ServerDb.IEC104MappingItem", b =>
                {
                    b.HasOne("PowerUnit.Infrastructure.IEC104ServerDb.IEC104ServerItem", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mappings_servers_server_id");

                    b.HasOne("PowerUnit.Infrastructure.IEC104ServerDb.IEC104TypeItem", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mappings_types_type_id");

                    b.Navigation("Server");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PowerUnit.Infrastructure.IEC104ServerDb.IEC104ServerItem", b =>
                {
                    b.HasOne("PowerUnit.Infrastructure.IEC104ServerDb.IEC104ServerApplicationLayerOptionItem", "ApplicationLayerOption")
                        .WithMany("IEC104ServerItems")
                        .HasForeignKey("ApplicationLayerOptionId")
                        .HasConstraintName("fk_servers_application_layer_options_application_layer_option_id");

                    b.HasOne("PowerUnit.Infrastructure.IEC104ServerDb.IEC104ServerChannelLayerOptionItem", "ChannelLayerOption")
                        .WithMany("ServerItems")
                        .HasForeignKey("ChannelLayerOptionId")
                        .HasConstraintName("fk_servers_channel_layer_options_channel_layer_option_id");

                    b.Navigation("ApplicationLayerOption");

                    b.Navigation("ChannelLayerOption");
                });

            modelBuilder.Entity("PowerUnit.Infrastructure.IEC104ServerDb.IEC104ServerApplicationLayerOptionItem", b =>
                {
                    b.Navigation("IEC104ServerItems");
                });

            modelBuilder.Entity("PowerUnit.Infrastructure.IEC104ServerDb.IEC104ServerChannelLayerOptionItem", b =>
                {
                    b.Navigation("ServerItems");
                });
#pragma warning restore 612, 618
        }
    }
}
