// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PowerUnit.Infrastructure.IEC104ServerDb;

#nullable disable

namespace PowerUnit.Infrastructure.IEC104ServerDb.Migrations
{
    [DbContext(typeof(PowerUnitIEC104ServerDbContext))]
    [Migration("20250823124450_Migration_00002_Rename")]
    partial class Migration_00002_Rename
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pu_iec104_server")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PowerUnit.Infrastructure.IEC104ServerDb.IEC104GroupItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte>("Group")
                        .HasColumnType("smallint")
                        .HasColumnName("group");

                    b.Property<long>("IEC104MappingId")
                        .HasColumnType("bigint")
                        .HasColumnName("iec104mapping_id");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("Group")
                        .HasDatabaseName("ix_groups_group");

                    b.HasIndex("IEC104MappingId")
                        .HasDatabaseName("ix_groups_iec104mapping_id");

                    b.ToTable("groups", "pu_iec104_server");
                });

            modelBuilder.Entity("PowerUnit.Infrastructure.IEC104ServerDb.IEC104MappingItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Address")
                        .HasColumnType("integer")
                        .HasColumnName("address");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("equipment_id");

                    b.Property<int>("IEC104TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("iec104type_id");

                    b.Property<string>("ParameterId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("parameter_id");

                    b.Property<int>("ServerId")
                        .HasColumnType("integer")
                        .HasColumnName("server_id");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasDefaultValue("")
                        .HasColumnName("source_id");

                    b.HasKey("Id")
                        .HasName("pk_mappings");

                    b.HasIndex("IEC104TypeId")
                        .HasDatabaseName("ix_mappings_iec104type_id");

                    b.HasIndex("ServerId", "SourceId", "EquipmentId", "ParameterId", "Address", "IEC104TypeId")
                        .IsUnique()
                        .HasDatabaseName("ix_mappings_server_id_source_id_equipment_id_parameter_id_addr");

                    b.ToTable("mappings", "pu_iec104_server");
                });

            modelBuilder.Entity("PowerUnit.Infrastructure.IEC104ServerDb.IEC104ServerApplicationLayerOptionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CheckCommonASDUAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("check_common_asdu_address");

                    b.Property<bool>("SporadicSendEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("sporadic_send_enabled");

                    b.HasKey("Id")
                        .HasName("pk_application_layer_options");

                    b.ToTable("application_layer_options", "pu_iec104_server");
                });

            modelBuilder.Entity("PowerUnit.Infrastructure.IEC104ServerDb.IEC104ServerChannelLayerOptionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxQueueSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("max_queue_size");

                    b.Property<byte>("Timeout0Sec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)30)
                        .HasColumnName("timeout0sec");

                    b.Property<byte>("Timeout1Sec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)15)
                        .HasColumnName("timeout1sec");

                    b.Property<byte>("Timeout2Sec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)10)
                        .HasColumnName("timeout2sec");

                    b.Property<byte>("Timeout3Sec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)20)
                        .HasColumnName("timeout3sec");

                    b.Property<bool>("UseFragmentSend")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("use_fragment_send");

                    b.Property<int>("WindowKSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(12)
                        .HasColumnName("window_k_size");

                    b.Property<int>("WindowWSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(8)
                        .HasColumnName("window_w_size");

                    b.HasKey("Id")
                        .HasName("pk_channel_layer_options");

                    b.ToTable("channel_layer_options", "pu_iec104_server");
                });

            modelBuilder.Entity("PowerUnit.Infrastructure.IEC104ServerDb.IEC104ServerItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationLayerOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("application_layer_option_id");

                    b.Property<int>("ChannelLayerOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("channel_layer_option_id");

                    b.Property<int>("CommonASDUAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("common_asdu_address");

                    b.Property<bool>("Enable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("")
                        .HasColumnName("name");

                    b.Property<int>("Port")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2404)
                        .HasColumnName("port");

                    b.HasKey("Id")
                        .HasName("pk_servers");

                    b.HasIndex("ApplicationLayerOptionId")
                        .HasDatabaseName("ix_servers_application_layer_option_id");

                    b.HasIndex("ChannelLayerOptionId")
                        .HasDatabaseName("ix_servers_channel_layer_option_id");

                    b.ToTable("servers", "pu_iec104_server");
                });

            modelBuilder.Entity("PowerUnit.Infrastructure.IEC104ServerDb.IEC104TypeItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_types");

                    b.ToTable("types", "pu_iec104_server");
                });

            modelBuilder.Entity("PowerUnit.Infrastructure.IEC104ServerDb.IEC104GroupItem", b =>
                {
                    b.HasOne("PowerUnit.Infrastructure.IEC104ServerDb.IEC104MappingItem", "IEC104Mapping")
                        .WithMany()
                        .HasForeignKey("IEC104MappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_groups_mappings_iec104mapping_id");

                    b.Navigation("IEC104Mapping");
                });

            modelBuilder.Entity("PowerUnit.Infrastructure.IEC104ServerDb.IEC104MappingItem", b =>
                {
                    b.HasOne("PowerUnit.Infrastructure.IEC104ServerDb.IEC104TypeItem", "IEC104Type")
                        .WithMany()
                        .HasForeignKey("IEC104TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mappings_types_iec104type_id");

                    b.HasOne("PowerUnit.Infrastructure.IEC104ServerDb.IEC104ServerItem", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mappings_servers_server_id");

                    b.Navigation("IEC104Type");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("PowerUnit.Infrastructure.IEC104ServerDb.IEC104ServerItem", b =>
                {
                    b.HasOne("PowerUnit.Infrastructure.IEC104ServerDb.IEC104ServerApplicationLayerOptionItem", "ApplicationLayerOption")
                        .WithMany("IEC104ServerItems")
                        .HasForeignKey("ApplicationLayerOptionId")
                        .HasConstraintName("fk_servers_application_layer_options_application_layer_option_");

                    b.HasOne("PowerUnit.Infrastructure.IEC104ServerDb.IEC104ServerChannelLayerOptionItem", "ChannelLayerOption")
                        .WithMany("IEC104ServerItems")
                        .HasForeignKey("ChannelLayerOptionId")
                        .HasConstraintName("fk_servers_channel_layer_options_channel_layer_option_id");

                    b.Navigation("ApplicationLayerOption");

                    b.Navigation("ChannelLayerOption");
                });

            modelBuilder.Entity("PowerUnit.Infrastructure.IEC104ServerDb.IEC104ServerApplicationLayerOptionItem", b =>
                {
                    b.Navigation("IEC104ServerItems");
                });

            modelBuilder.Entity("PowerUnit.Infrastructure.IEC104ServerDb.IEC104ServerChannelLayerOptionItem", b =>
                {
                    b.Navigation("IEC104ServerItems");
                });
#pragma warning restore 612, 618
        }
    }
}
