// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

using PowerUnit.Infrastructure.IEC104ServerDb;

#nullable disable

namespace PowerUnit.Migrations
{
    [DbContext(typeof(PowerUnitIEC104ServerDbContext))]
    partial class PowerUnitIEC104ServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pu_iec104_server")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PowerUnit.IEC104GroupItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte>("Group")
                        .HasColumnType("smallint")
                        .HasColumnName("group");

                    b.Property<long>("IEC104MappingId")
                        .HasColumnType("bigint")
                        .HasColumnName("iec104mapping_id");

                    b.HasKey("Id")
                        .HasName("pk_iec104groups");

                    b.HasIndex("Group")
                        .HasDatabaseName("ix_iec104groups_group");

                    b.HasIndex("IEC104MappingId")
                        .HasDatabaseName("ix_iec104groups_iec104mapping_id");

                    b.ToTable("iec104groups", "pu_iec104_server");
                });

            modelBuilder.Entity("PowerUnit.IEC104MappingItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Address")
                        .HasColumnType("integer")
                        .HasColumnName("address");

                    b.Property<long>("EquipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("equipment_id");

                    b.Property<int>("IEC104TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("iec104type_id");

                    b.Property<long>("ParameterId")
                        .HasColumnType("bigint")
                        .HasColumnName("parameter_id");

                    b.Property<int>("ServerId")
                        .HasColumnType("integer")
                        .HasColumnName("server_id");

                    b.HasKey("Id")
                        .HasName("pk_iec104mappings");

                    b.HasIndex("IEC104TypeId")
                        .HasDatabaseName("ix_iec104mappings_iec104type_id");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_iec104mappings_server_id");

                    b.ToTable("iec104mappings", "pu_iec104_server");
                });

            modelBuilder.Entity("PowerUnit.IEC104ServerApplicationLayerOptionItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<bool>("CheckCommonASDUAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("check_common_asdu_address");

                    b.Property<bool>("SporadicSendEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("sporadic_send_enabled");

                    b.HasKey("Id")
                        .HasName("pk_iec104server_application_layer_options");

                    b.ToTable("iec104server_application_layer_options", "pu_iec104_server");
                });

            modelBuilder.Entity("PowerUnit.IEC104ServerChannelLayerOptionItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<byte>("Timeout0Sec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)30)
                        .HasColumnName("timeout0sec");

                    b.Property<byte>("Timeout1Sec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)15)
                        .HasColumnName("timeout1sec");

                    b.Property<byte>("Timeout2Sec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)10)
                        .HasColumnName("timeout2sec");

                    b.Property<byte>("Timeout3Sec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)20)
                        .HasColumnName("timeout3sec");

                    b.Property<bool>("UseFragmentSend")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("use_fragment_send");

                    b.Property<int>("WindowKSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(12)
                        .HasColumnName("window_k_size");

                    b.Property<int>("WindowWSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(8)
                        .HasColumnName("window_w_size");

                    b.HasKey("Id")
                        .HasName("pk_iec104server_channel_layer_options");

                    b.ToTable("iec104server_channel_layer_options", "pu_iec104_server");
                });

            modelBuilder.Entity("PowerUnit.IEC104ServerItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommonASDUAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("common_asdu_address");

                    b.Property<bool>("Enable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("")
                        .HasColumnName("name");

                    b.Property<int>("Port")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2404)
                        .HasColumnName("port");

                    b.HasKey("Id")
                        .HasName("pk_iec104servers");

                    b.ToTable("iec104servers", "pu_iec104_server");
                });

            modelBuilder.Entity("PowerUnit.IEC104TypeItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_iec104types");

                    b.ToTable("iec104types", "pu_iec104_server");
                });

            modelBuilder.Entity("PowerUnit.IEC104GroupItem", b =>
                {
                    b.HasOne("PowerUnit.IEC104MappingItem", "IEC104Mapping")
                        .WithMany()
                        .HasForeignKey("IEC104MappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_iec104groups_iec104mappings_iec104mapping_id");

                    b.Navigation("IEC104Mapping");
                });

            modelBuilder.Entity("PowerUnit.IEC104MappingItem", b =>
                {
                    b.HasOne("PowerUnit.IEC104TypeItem", "IEC104Type")
                        .WithMany()
                        .HasForeignKey("IEC104TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_iec104mappings_iec104types_iec104type_id");

                    b.HasOne("PowerUnit.IEC104ServerItem", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_iec104mappings_iec104servers_server_id");

                    b.Navigation("IEC104Type");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("PowerUnit.IEC104ServerApplicationLayerOptionItem", b =>
                {
                    b.HasOne("PowerUnit.IEC104ServerItem", null)
                        .WithOne("ApplicationLayerOption")
                        .HasForeignKey("PowerUnit.IEC104ServerApplicationLayerOptionItem", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_iec104server_application_layer_options_iec104servers_id");
                });

            modelBuilder.Entity("PowerUnit.IEC104ServerChannelLayerOptionItem", b =>
                {
                    b.HasOne("PowerUnit.IEC104ServerItem", null)
                        .WithOne("ChannelLayerOption")
                        .HasForeignKey("PowerUnit.IEC104ServerChannelLayerOptionItem", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_iec104server_channel_layer_options_iec104servers_id");
                });

            modelBuilder.Entity("PowerUnit.IEC104ServerItem", b =>
                {
                    b.Navigation("ApplicationLayerOption");

                    b.Navigation("ChannelLayerOption");
                });
#pragma warning restore 612, 618
        }
    }
}
