//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerUnit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerUnit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одноэлементная информация без метки времени.
        /// </summary>
        internal static string _001_M_SP_NA_1_Desc {
            get {
                return ResourceManager.GetString("_001_M_SP_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одноэлементная информация с меткой времени.
        /// </summary>
        internal static string _002_M_SP_TA_1_Desc {
            get {
                return ResourceManager.GetString("_002_M_SP_TA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Двухэлементная информация без метки времени.
        /// </summary>
        internal static string _003_M_DP_NA_1_Desc {
            get {
                return ResourceManager.GetString("_003_M_DP_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Двухэлементная информация с меткой времени.
        /// </summary>
        internal static string _004_M_DP_TA_1_Desc {
            get {
                return ResourceManager.GetString("_004_M_DP_TA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о положении отпаек.
        /// </summary>
        internal static string _005_M_ST_NA_1_Desc {
            get {
                return ResourceManager.GetString("_005_M_ST_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о положении отпаек с меткой времени.
        /// </summary>
        internal static string _006_M_ST_TA_1_Desc {
            get {
                return ResourceManager.GetString("_006_M_ST_TA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строка из 32 бит.
        /// </summary>
        internal static string _007_M_BO_NA_1_Desc {
            get {
                return ResourceManager.GetString("_007_M_BO_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строка из 32 бит с меткой времени.
        /// </summary>
        internal static string _008_М_ВО_ТА_1_Desc {
            get {
                return ResourceManager.GetString("_008_М_ВО_ТА_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение измеряемой величины, нормализованное значение.
        /// </summary>
        internal static string _009_M_ME_NA_1_Desc {
            get {
                return ResourceManager.GetString("_009_M_ME_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение измеряемой величины, нормализованное значение с меткой времени.
        /// </summary>
        internal static string _010_М_МЕ_ТА_1_Desc {
            get {
                return ResourceManager.GetString("_010_М_МЕ_ТА_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение измеряемой величины, масштабированное значение.
        /// </summary>
        internal static string _011_M_ME_NB_1_Desc {
            get {
                return ResourceManager.GetString("_011_M_ME_NB_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение измеряемой величины, масштабированное значение с меткой времени.
        /// </summary>
        internal static string _012_М_МЕ_ТВ_1_Desc {
            get {
                return ResourceManager.GetString("_012_М_МЕ_ТВ_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение измеряемой величины, короткий формате плавающей запятой.
        /// </summary>
        internal static string _013_M_ME_NC_1_Desc {
            get {
                return ResourceManager.GetString("_013_M_ME_NC_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение измеряемой величины, короткий формат с плавающей запятой с меткой времени.
        /// </summary>
        internal static string _014_М_МЕ_ТС_1_Desc {
            get {
                return ResourceManager.GetString("_014_М_МЕ_ТС_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интегральные суммы.
        /// </summary>
        internal static string _015_M_IT_NA_1_Desc {
            get {
                return ResourceManager.GetString("_015_M_IT_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интегральные суммы с меткой времени.
        /// </summary>
        internal static string _016_М_IТ_ТА_1_Desc {
            get {
                return ResourceManager.GetString("_016_М_IТ_ТА_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работа устройств защиты с меткой времени.
        /// </summary>
        internal static string _017_М_ЕР_ТА_1_Desc {
            get {
                return ResourceManager.GetString("_017_М_ЕР_ТА_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Упакованная информация о срабатывании пусковых органов устройств защиты с меткой времени.
        /// </summary>
        internal static string _018_М_ЕР_ТВ_1_Desc {
            get {
                return ResourceManager.GetString("_018_М_ЕР_ТВ_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Упакованная информация о срабатывании выходных цепей устройства защиты с меткой времени.
        /// </summary>
        internal static string _019_М_ЕР_ТС_1_Desc {
            get {
                return ResourceManager.GetString("_019_М_ЕР_ТС_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Упакованная одноэлементная информация с указателем изменения состояния.
        /// </summary>
        internal static string _020_M_PS_NA_1_Desc {
            get {
                return ResourceManager.GetString("_020_M_PS_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение измеряемой величины, нормализованное значение без описателя качества.
        /// </summary>
        internal static string _021_M_ME_ND_1_Desc {
            get {
                return ResourceManager.GetString("_021_M_ME_ND_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одноэлементная информация с меткой времени СР56Время2а.
        /// </summary>
        internal static string _030_M_SP_TB_1_Desc {
            get {
                return ResourceManager.GetString("_030_M_SP_TB_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Двухэлементная информация с меткой времени СР56Время2а.
        /// </summary>
        internal static string _031_M_DP_TB_1_Desc {
            get {
                return ResourceManager.GetString("_031_M_DP_TB_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о положении отпаек с меткой времени СР56Время2а.
        /// </summary>
        internal static string _032_M_ST_TB_1_Desc {
            get {
                return ResourceManager.GetString("_032_M_ST_TB_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строка из 32 б и тс меткой времени СР56Время2а.
        /// </summary>
        internal static string _033_М_ВО_ТВ_1_Desc {
            get {
                return ResourceManager.GetString("_033_М_ВО_ТВ_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение измеряемой величины, нормализованное значение с меткой времени СР56Время2а.
        /// </summary>
        internal static string _034_M_ME_TD_1_Desc {
            get {
                return ResourceManager.GetString("_034_M_ME_TD_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение измеряемой величины, масштабированное значение с меткой времени СР56Время2а.
        /// </summary>
        internal static string _035_М_МЕ_ТЕ_1_Desc {
            get {
                return ResourceManager.GetString("_035_М_МЕ_ТЕ_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение измеряемой величины, короткий формат с плавающей запятой с меткой времени СР56Время2а.
        /// </summary>
        internal static string _036_M_ME_TF_1_Desc {
            get {
                return ResourceManager.GetString("_036_M_ME_TF_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интегральные суммы с меткой времени СР56Время2а.
        /// </summary>
        internal static string _037_М_IТ_ТВ_1_Desc {
            get {
                return ResourceManager.GetString("_037_М_IТ_ТВ_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работа устройств защиты с меткой времени СР56Время2а.
        /// </summary>
        internal static string _038_M_EP_TD_1_Desc {
            get {
                return ResourceManager.GetString("_038_M_EP_TD_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Упакованное сообщение о срабатывании пусковых органов устройств защиты с меткой времени СР56Время2а.
        /// </summary>
        internal static string _039_М_ЕР_ТЕ_1_Desc {
            get {
                return ResourceManager.GetString("_039_М_ЕР_ТЕ_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Упакованная информация о срабатывании в выходных цепях устройства защиты с меткой времени СР56Время2а.
        /// </summary>
        internal static string _040_M_EP_TF_1_Desc {
            get {
                return ResourceManager.GetString("_040_M_EP_TF_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Однопозиционная команда.
        /// </summary>
        internal static string _045_C_SC_NA_1_Desc {
            get {
                return ResourceManager.GetString("_045_C_SC_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Двухпозиционная команда.
        /// </summary>
        internal static string _046_C_DC_NA_1_Desc {
            get {
                return ResourceManager.GetString("_046_C_DC_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда пошагового регулирования.
        /// </summary>
        internal static string _047_C_RC_NA_1_Desc {
            get {
                return ResourceManager.GetString("_047_C_RC_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда уставки, нормализованное значение.
        /// </summary>
        internal static string _048_C_SE_NA_1_Desc {
            get {
                return ResourceManager.GetString("_048_C_SE_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда уставки, масштабированное значение.
        /// </summary>
        internal static string _049_C_SE_NB_1_Desc {
            get {
                return ResourceManager.GetString("_049_C_SE_NB_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда уставки, короткий формат с плавающей запятой.
        /// </summary>
        internal static string _050_C_SE_NC_1_Desc {
            get {
                return ResourceManager.GetString("_050_C_SE_NC_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строка из 32 бит.
        /// </summary>
        internal static string _051_C_BO_NA_1_Desc {
            get {
                return ResourceManager.GetString("_051_C_BO_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Однопозиционная команда с меткой времени СР56Время2а.
        /// </summary>
        internal static string _058_C_SC_TA_1_Desc {
            get {
                return ResourceManager.GetString("_058_C_SC_TA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Двухпозиционная команда с меткой времени СР56Время2а.
        /// </summary>
        internal static string _059_C_DC_TA_1_Desc {
            get {
                return ResourceManager.GetString("_059_C_DC_TA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда пошагового ругулирования с меткой времени СР56Время2а.
        /// </summary>
        internal static string _060_C_RC_TA_1_Desc {
            get {
                return ResourceManager.GetString("_060_C_RC_TA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда уставки с меткой времени СР56Время2а.
        /// </summary>
        internal static string _061_C_SE_TA_1_Desc {
            get {
                return ResourceManager.GetString("_061_C_SE_TA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда уставки с меткой времени СР56Время2а, масштабированное значение.
        /// </summary>
        internal static string _062_C_SE_TB_1_Desc {
            get {
                return ResourceManager.GetString("_062_C_SE_TB_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда уставки с меткой времени СР56Время2а, короткий формат с плавающей запятой.
        /// </summary>
        internal static string _063_C_SE_TC_1_Desc {
            get {
                return ResourceManager.GetString("_063_C_SE_TC_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строка из 32 битов с меткой времени СР56Время2а.
        /// </summary>
        internal static string _064_C_BO_TA_1_Desc {
            get {
                return ResourceManager.GetString("_064_C_BO_TA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Окончание инициализации.
        /// </summary>
        internal static string _070_M_EI_NA_1_Desc {
            get {
                return ResourceManager.GetString("_070_M_EI_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда опроса.
        /// </summary>
        internal static string _100_C_IC_NA_1_Desc {
            get {
                return ResourceManager.GetString("_100_C_IC_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда опроса счетчиков.
        /// </summary>
        internal static string _101_C_CI_NA_1_Desc {
            get {
                return ResourceManager.GetString("_101_C_CI_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда чтения.
        /// </summary>
        internal static string _102_C_RD_NA_1_Desc {
            get {
                return ResourceManager.GetString("_102_C_RD_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда синхронизации часов.
        /// </summary>
        internal static string _103_C_CS_NA_1_Desc {
            get {
                return ResourceManager.GetString("_103_C_CS_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестовая команда.
        /// </summary>
        internal static string _104_C_TS_NA_1_Desc {
            get {
                return ResourceManager.GetString("_104_C_TS_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда установки процесса в исходное состояние.
        /// </summary>
        internal static string _105_C_RP_NA_1_Desc {
            get {
                return ResourceManager.GetString("_105_C_RP_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда определения запаздывания.
        /// </summary>
        internal static string _106_C_CD_NA_1_Desc {
            get {
                return ResourceManager.GetString("_106_C_CD_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестовая команда с меткой времени СР56Время2а.
        /// </summary>
        internal static string _107_C_TS_TA_1_Desc {
            get {
                return ResourceManager.GetString("_107_C_TS_TA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры измеряемых величин, нормализованное значение.
        /// </summary>
        internal static string _110_P_ME_NA_1_Desc {
            get {
                return ResourceManager.GetString("_110_P_ME_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры измеряемых величин, масштабированное значение.
        /// </summary>
        internal static string _111_P_ME_NB_1_Desc {
            get {
                return ResourceManager.GetString("_111_P_ME_NB_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры измеряемых величин, короткий формате плавающей запятой.
        /// </summary>
        internal static string _112_P_ME_NC_1_Desc {
            get {
                return ResourceManager.GetString("_112_P_ME_NC_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активация параметра.
        /// </summary>
        internal static string _113_P_AC_NA_1_Desc {
            get {
                return ResourceManager.GetString("_113_P_AC_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готовность файла.
        /// </summary>
        internal static string _120_F_FR_NA_1_Desc {
            get {
                return ResourceManager.GetString("_120_F_FR_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готовность секции.
        /// </summary>
        internal static string _121_F_SR_NA_1_Desc {
            get {
                return ResourceManager.GetString("_121_F_SR_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вызов директории, выбор файла, вызов секции.
        /// </summary>
        internal static string _122_F_SC_NA_1_Desc {
            get {
                return ResourceManager.GetString("_122_F_SC_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последняя секция, последний сегмент.
        /// </summary>
        internal static string _123_F_LS_NA_1_Desc {
            get {
                return ResourceManager.GetString("_123_F_LS_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение приема файла, подтверждение приема секции.
        /// </summary>
        internal static string _124_F_AF_NA_1_Desc {
            get {
                return ResourceManager.GetString("_124_F_AF_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сегмент.
        /// </summary>
        internal static string _125_F_SG_NA_1_Desc {
            get {
                return ResourceManager.GetString("_125_F_SG_NA_1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Директория.
        /// </summary>
        internal static string _126_F_DR_TA_1_Desc {
            get {
                return ResourceManager.GetString("_126_F_DR_TA_1_Desc", resourceCulture);
            }
        }
    }
}
